//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleValidator_Proto.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSVData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSVData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuleValidator_Proto.Tests.CSVData", typeof(CSVData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,group_customer,Receiving_Country_Code,Shipping_Country_Code,Shipping_Company,Receving_Company,Shipping_PostalCode,Receiving_PostalCode
        ///3,LTSHoldings,SE,SE,*,LTS*,*,21124,3,LTSHoldings,1,SE,SE,*,LTS*,*,21124,MLM31,MLM31,Domestic,10,SEK,MLM31 Domestic,Domestic VAT,0
        ///4,LTSHoldings,SE,SE,*,*,*,*,4,LTSHoldings,2,SE,SE,*,*,*,*,MLM20,MLM20,Domestic,10,SEK,MLM20 Domestic,Domestic VAT,0
        ///5,LTSHoldings,SE,EU,*,LTS*,*,21124,5,LTSHoldings,3,EU,SE,*,LTS*,*,21124,MLM31 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RuleList {
            get {
                return ResourceManager.GetString("RuleList", resourceCulture);
            }
        }
    }
}
