
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RuleValidator_Proto.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Article
{

    public int Id { get; set; }

    public string Url { get; set; }

    public string ArticleNumber { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> PurchasePrice { get; set; }

    public string Unit { get; set; }

    public Nullable<decimal> VAT { get; set; }

    public bool Expired { get; set; }

}

}
