
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RuleValidator_Proto.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Currency
{

    public int Id { get; set; }

    public string Url { get; set; }

    public Nullable<decimal> BuyRate { get; set; }

    public string Code { get; set; }

    public System.DateTime Date { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> SellRate { get; set; }

    public decimal Unit { get; set; }

}

}
