
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RuleValidator_Proto.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public int Id { get; set; }

    public string Url { get; set; }

    public string City { get; set; }

    public string Comments { get; set; }

    public string CountryCode { get; set; }

    public string CustomerNumber { get; set; }

    public string Name { get; set; }

    public string OrganizationNumber { get; set; }

    public bool HoldingCompany { get; set; }

}

}
