
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RuleValidator_Proto.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class File
{

    public File()
    {

        this.ImportedItems = new HashSet<ImportedItem>();

        this.ExportedItems = new HashSet<ExportedItem>();

    }


    public int Id { get; set; }

    public string filename { get; set; }

    public string Group { get; set; }

    public string remarks { get; set; }

    public string group_customer { get; set; }

    public bool rules_applied { get; set; }

    public bool exported { get; set; }

    public Nullable<System.DateTime> uploadedDateTime { get; set; }

    public Nullable<System.DateTime> ImportedDateTime { get; set; }

    public Nullable<System.DateTime> ExportedDateTime { get; set; }

    public bool Locked { get; set; }

    public bool Deleted { get; set; }



    public virtual ICollection<ImportedItem> ImportedItems { get; set; }

    public virtual ICollection<ExportedItem> ExportedItems { get; set; }

}

}
