
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RuleValidator_Proto.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ImportedItem
{

    public long Id { get; set; }

    public int File_Id { get; set; }

    public string Consignment_Number { get; set; }

    public string Shipping_Company_Name { get; set; }

    public string Shipping_Postal_Code { get; set; }

    public string Shipping_City { get; set; }

    public string Shipping_Country_Code { get; set; }

    public string Receiving_Company_Name { get; set; }

    public string Receiving_Postal_Code { get; set; }

    public string Receiving_City { get; set; }

    public string Receiving_Country_Code { get; set; }

    public Nullable<decimal> Total_Number_Of_Packages { get; set; }

    public Nullable<decimal> Total_Weight { get; set; }

    public Nullable<decimal> Total_Volume { get; set; }

    public Nullable<decimal> Total_Loading_Meters { get; set; }

    public Nullable<decimal> Total_Pallet_Space { get; set; }

    public Nullable<System.DateTime> Date_Registered { get; set; }

    public string Shippers_Reference { get; set; }

    public string Consignee_Reference { get; set; }

    public Nullable<decimal> Calculated_Price { get; set; }



    public virtual File File { get; set; }

}

}
