
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RuleValidator_Proto.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class RuleList
{

    public int Id { get; set; }

    public string Group { get; set; }

    public int Number { get; set; }

    public string Shipping_Country_Code { get; set; }

    public string Receiving_Country_Code { get; set; }

    public string Shipping_Company { get; set; }

    public string Receving_Company { get; set; }

    public string Shipping_PostalCode { get; set; }

    public string Receiving_PostalCode { get; set; }

    public string Responsible_Site { get; set; }

    public string Paying_Site { get; set; }

    public string Category { get; set; }

    public string Article_Number { get; set; }

    public string Article_Description { get; set; }

    public string Transaction_Type { get; set; }

    public string Currency { get; set; }

    public string Invoice_Template { get; set; }

    public bool VAT { get; set; }

}

}
